(() => {
const dialog=document.getElementById('projectDialog');if(!dialog)return;
const content=document.getElementById('projectContent');let opener;
const text={en:{intro:'Explore video edits, visual samples and interactive concept demos.',demo:'Concept demo',video:'Showreel'},ar:{intro:'استكشف نماذج مونتاج الفيديو والتصاميم والنماذج التفاعلية.',demo:'نموذج تجريبي',video:'عرض مونتاج'}};
function localize(){const lang=document.documentElement.lang==='ar'?'ar':'en';document.querySelectorAll('[data-work-text]').forEach(el=>el.textContent=text[lang][el.dataset.workText]);}
new MutationObserver(localize).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});localize();
const descriptions={estate:['Interactive real estate concept — sample listings and viewing requests.','نموذج موقع عقاري تفاعلي — عقارات تجريبية وطلب معاينة.'],store:['Interactive store concept — product selection and a demo shopping bag.','نموذج متجر تفاعلي — اختيار المنتجات وسلة تجريبية.'],portfolio:['Designer portfolio concept — selected design studies and project details.','نموذج معرض مصمم — تصاميم تجريبية وتفاصيل المشاريع.'],support:['Support agent interface demo with scripted local replies; no live AI service connected.','نموذج واجهة مساعد دعم بردود تجريبية محلية؛ غير متصل بخدمة ذكاء اصطناعي.'],visuals:['Visual samples supplied for this portfolio; explore both designs in full.','نماذج التصاميم المرفقة للمعرض؛ افتح الصورتين بالحجم الكامل.'],brand:['Uploaded before-and-after video editing showcase.','عرض مونتاج قبل وبعد من الفيديو المرفق.'],product:['Uploaded before-and-after video editing showcase.','عرض مونتاج قبل وبعد من الفيديو المرفق.'],campaign:['Campaign concept using the same Brand Reel editing sample.','نموذج حملة يستخدم فيديو المونتاج نفسه الموجود في Brand Reel.']};
function stopPreviews(){document.querySelectorAll('.work video').forEach(v=>v.pause());}
function playPreview(v){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;if(!v.src)v.src=v.dataset.src;v.play().catch(()=>{});}
document.querySelectorAll('.project-open').forEach(button=>{const v=button.querySelector('video');if(v){button.addEventListener('mouseenter',()=>playPreview(v));button.addEventListener('mouseleave',()=>{v.pause();v.currentTime=0;});button.addEventListener('focus',()=>playPreview(v));button.addEventListener('blur',()=>v.pause());}button.addEventListener('click',()=>{
stopPreviews();opener=button;const card=button.closest('.work'),id=card.dataset.project;const ar=document.documentElement.lang==='ar';document.getElementById('projectTitle').textContent=card.querySelector('b').textContent;document.getElementById('projectSummary').textContent=descriptions[id][ar?1:0];content.replaceChildren();
if(['estate','store','portfolio','support'].includes(id)){const frame=document.createElement('iframe');frame.src='demos/'+id+'.html';frame.title=card.querySelector('b').textContent;content.append(frame);}else if(id==='visuals'){const gallery=document.createElement('div');gallery.className='visual-gallery';[['construction-visual.jpeg',ar?'تصميم إنشائي':'Construction visual'],['robotics-visual.jpeg',ar?'تصميم الروبوتات والذكاء الاصطناعي':'Robotics & AI visual']].forEach(([src,label])=>{const figure=document.createElement('figure'),a=document.createElement('a'),img=document.createElement('img'),caption=document.createElement('figcaption');a.href='assets/work/'+src;a.target='_blank';a.rel='noopener';img.src=a.href;img.alt=label;caption.textContent=label;a.append(img);figure.append(a,caption);gallery.append(figure);});content.append(gallery);}else{const video=document.createElement('video');video.src='assets/work/'+(id==='product'?'product-launch.mp4':'brand-reel.mp4');video.controls=true;video.playsInline=true;video.preload='metadata';video.poster=button.querySelector('video').poster;content.append(video);video.play().catch(()=>{});}
dialog.showModal();document.body.style.overflow='hidden';document.getElementById('projectClose').focus();});});
function cleanup(){content.querySelectorAll('video').forEach(v=>v.pause());content.replaceChildren();document.body.style.overflow='';if(opener)opener.focus();}
document.getElementById('projectClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',cleanup);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});document.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',stopPreviews));document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPreviews();content.querySelectorAll('video').forEach(v=>v.pause());}});
})();